### ISSUE TITLE
alpTrader - Error at line 770

### ISSUE THREAD

**Issue by rmss2411** [scarplus/signals#2]
Hey,

Like you asked in discord, here are the log files:

[Tradelogfile.txt](https://github.com/scarplus/signals/files/11515297/Tradelogfile.txt)
[Tradelogfile.txt](https://github.com/scarplus/signals/files/11515299/Tradelogfile.txt)
[Tradelogfile.txt](https://github.com/scarplus/signals/files/11515301/Tradelogfile.txt)

**Comment by scarplus** [comment]
It is mostly due to cash only account(no margin). In cash only it's likely that broker is preventing trades with unsettled funds. Test it by manually placing a trade in their platform to ensure it really prevents the trade. In such case I would suggest set below param in config.inj to 47% .. so it is below 50% of funds being used for trading and does not use unsettled funds for trading.

PERCENTAGE_OF_ABOVE_TO_BE_USED = 47

**Comment by jkozlow3** [comment]
Good point visay.  On my 1 cash account in TDA, I limit it to 47% for daily trading as well.  rmss2411 - do you have margin enabled and enough money in the account to qualify for margin?

**Comment by rmss2411** [comment]
That could be the issue. I have no margin allowed, so I was using the configuration at 100%. I will try to drop it and see if it solves that Error, that could be it.
Thank you guys.

**Comment by perfektoa** [comment]
[Tradelogfile.txt](https://github.com/scarplus/signals/files/11520866/Tradelogfile.txt)
[configastxtforgithub.txt](https://github.com/scarplus/signals/files/11520870/configastxtforgithub.txt)
my trade log from today and config used today, since we are both getting the same error.

**Comment by scarplus** [comment]
I think yours is failing before inverse calculations. Two options to debug
1. Try CANCEL_INVERSE_ALLOCATIONS=NO
2. Place stockinverse.txt in both folders ( where shortcut and also in the underneath folder where shortcut points to)

If you run your program manually on command prompt it must show trace logs on console. If you could see it please share it so i can triage further.

**Comment by perfektoa** [comment]
Sorry for my ignorance, I can't figure out how to find the trace logs on console. Mine runs then closes as soon as it finishes even when I manually run it with command prompt. I don't know how to find the trace logs.

**Comment by jkozlow3** [comment]
> Sorry for my ignorance, I can't figure out how to find the trace logs on console. Mine runs then closes as soon as it finishes even when I manually run it with command prompt. I don't know how to find the trace logs.

[configastxtforgithub.txt](https://github.com/scarplus/signals/files/11525941/configastxtforgithub.txt)

Can you try this config file (make a backup of yours first).  It's in DEBUG mode.  Right-click on the shortcut and make sure it is pointing to the right path of the EXE and then right-click the shortcut and run as an administrator.

**Comment by rmss2411** [comment]
Today tried to do with lower equity %, still error at line 770. Even though the account had more than enough money to execute the trades (they required ~700 dollars total for an acc with 1000). This was also with a single ticker symphony.

**Comment by bpersino** [comment]
I am currently running paper trading in Alpaca as a test and am also getting the 770 error.  
[Tradelogfile.txt](https://github.com/scarplus/signals/files/11537912/Tradelogfile.txt)

**Comment by scarplus** [comment]
this param could be set wrong try with 
INVERSE_TICKERS_PAIR_FILE=../stockinverse.txt
or 
INVERSE_TICKERS_PAIR_FILE=stockinverse.txt
all relative path must be in reference to actual binary executed not the shortcut but the subfolder where actual alpTrade.exe is.
