### ISSUE TITLE
UnboundLocalError: local variable 'STOCKINVERSEREF' referenced before assignment

### ISSUE THREAD

**Issue by joshwigginton** [scarplus/signals#3]
I get the following error when I try CANCEL_INVERSE_ALLOCATIONS=NO

Traceback (most recent call last):
  File "alpTrade.py", line 731, in main
UnboundLocalError: local variable 'STOCKINVERSEREF' referenced before assignment

I've tried the following:

1. Copied stockinverse.txt to both the application folder and when the shortcut link and ini files are.
2. Typed the full path to the stockinverse.txt file. 

The application works fine when CANCEL_INVERSE_ALLOCATIONS=YES

**Comment by jkozlow3** [comment]
I'd suggest a simple workaround for now (I've never tried it with it set to "NO").  Keep it as "YES" but just put the following tickers in the file and remove all others if you don't want to cancel any inverse tickers:

XXX,YYY

**Comment by joshwigginton** [comment]
Great idea will do. 

Question: Does the Cancel Inverse Allocations:

1. Cancel any orders for ETFs that are short.
2. Attempt to balance long vs. short ETFs.... if you have one strategy that has TQQQ and another SQQQ, it will settle long or short based on the size of each. 

Not sure how it works.

**Comment by jkozlow3** [comment]
1. No
2. Yes

If you are running multiple symphonies and you are supposed to buy 30% TQQQ and 10% SQQQ (across the total portfolio), it subtracts the $$ equivalent of 10% SQQQ from the # of shares of TQQQ it purchases.  So you'll end up with 20% of your portfolio in TQQQ and that 10% that would have otherwise bought SQQQ will stay in cash.  This saves money on unnecessary fees and expense ratios.  3x leveraged ETFs charge a lot of hidden fees for the cost of the leverage, so the inverse ticker cancellation potentially saves a lot.  I highly recommend using it for this reason.  

You may need to add tickers to the list over time, depending on which tickers you use in your specific symphonies.  I know I added HIBL & HIBS to the list in my own copy.

**Comment by joshwigginton** [comment]
Awesome! Makes perfect sense to just keep as YES now. Thanks for the prompt responses.

**Comment by jkozlow3** [comment]
No problem.  Here's an example from the log file on a day that it performed an inverse ticker cancellation.



  Ticker   Price  NetTickerPercent
0   FNGU  186.01              69.0
1   HIBS   36.83              14.0
2   SQQQ   17.57               4.0
3   TECS   13.25               2.0
4   TQQQ   42.71              11.0

{'primary': 'inverse', 'QQQ': 'PSQ', 'BITO': 'BITI', 'ARKK': 'SARK', 'SPY': 'SH', 'UPRO': 'SPXU', 'TQQQ': 'SQQQ', 'UDOW': 'SDOW', 'SOXL': 'SOXS', 'SSO': 'SDS', 'SPXL': 'SPXS', 'TMF': 'TMV', 'TYD': 'TYO', 'UGE': 'SZK', 'TECL': 'TECS', 'QLD': 'QID', 'HIBL': 'HIBS'}

**TQQQ with allocation 11.0 has inverse of SQQQ with 4.0 allocation
{'BIL': 8.0, 'TQQQ': 7.0, 'SQQQ': 0}**

Allocations after Inverse adjustments
Ticker    Price  NetTickerPercent                        
FNGU    186.01              69.0
HIBS     36.83              14.0
SQQQ     17.57               0.0
TECS     13.25               2.0
TQQQ     42.71               7.0
BIL       1.00               8.0


You can see that it subtracted 4% allocation of TQQQ (it went from 11% to 7%).  The way Visay coded it, it actually redirects it to BIL.  But you can put BIL on the "skip list" and then it just holds cash instead.  That's the only way I've ever run it personally.

**Comment by joshwigginton** [comment]
Thanks - you seem very knowledge about the app. I'm trying to figure out a way to trade my own symphonies or my own curated list that are not in the googledrive list. Do you know how to do this by chance?

**Comment by jkozlow3** [comment]
Visay will add any symphony you'd like to his Signals Sheet if you ask him.

**Comment by scarplus** [comment]
mentioned error issue is fixed in version v7.
